### PR TITLE
version 4.9.3

### PR DESCRIPTION
**Pull request by matthiasdiener**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by matthiasdiener** [comment]
This is currently failing in Windows tests with

```
(%PREFIX%) %SRC_DIR%>"%PREFIX%\python.exe" -s "%SRC_DIR%\run_test.py" 
import: 'gmsh'
Traceback (most recent call last):
  File "D:\bld\gmsh-packages_1641598462356\test_tmp\run_test.py", line 2, in <module>
    import gmsh
  File "D:\bld\gmsh-packages_1641598462356\_test_env\lib\site-packages\gmsh.py", line 51, in <module>
    lib = CDLL(libpath)
  File "D:\bld\gmsh-packages_1641598462356\_test_env\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by isuruf** [comment]
https://gitlab.onelab.info/gmsh/gmsh/-/merge_requests/458

**Comment by matthiasdiener** [comment]
This is ready for review @conda-forge/gmsh

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by matthiasdiener** [comment]
@conda-forge-admin rerender

**Comment by matthiasdiener** [comment]
@conda-forge-admin rerender

**Pull request merged**
